### ISSUE TITLE
use ffmpeg6 on linux

### ISSUE THREAD

**Issue by YancyHsu** [rainyl/opencv.full#2]
https://github.com/rainyl/opencv.full/blob/471db009523ce46d04b9e07caeff7a66517f42a0/.github/workflows/build_test_release.yaml#L128

I have got libopencv-windows-x64.tar.gz, and tar it, then got a lot of .lib in  \x64\vc17\staticlib, but how to get .dll?
What should I do?

**Comment by YancyHsu** [comment]
I tried it in Windows 10, I revise the cmake to 3.29.6, compile and build is success

`self.tool_requires("cmake/3.29.6")`

**Comment by rainyl** [comment]
this repo builds opencv static libs, .lib are static libraries prepared for static linking to opencv_dart on windows, if you need dynamic libraries just download them from official releases of opencv.

but if you want to compile opencv_dart on linux, firstly compile this repo on linux, set OpenCV_DIR, and then compile opencv_dart.
