### ISSUE TITLE
enable vulkan

### ISSUE THREAD

**Issue by abdelaziz-mahdy** [rainyl/opencv.full#5]
do you think vulkan can be enabled?
https://github.com/rainyl/opencv.full/blob/899bc6989070a3cd92eb6bce176aa0fc8e258a9e/conanfile.py#L186

if it works correctly i think it will speed up dnn greatly, instead of opencl

**Comment by rainyl** [comment]
I am not sure whether vulkan needs extra dependencies like OpenVINO, will look into it later.

**Comment by abdelaziz-mahdy** [comment]
<img width="1002" alt="image" src="https://github.com/user-attachments/assets/27b4bfad-6792-496e-8d03-7cd5d13d5026">
this is from https://docs.opencv.org/4.x/db/d05/tutorial_config_reference.html

take your time. i found it so i wanted to check if it improved performance since it will be better than opencl i think

**Comment by rainyl** [comment]
Oh, great, then let's see the result of CI, if no errors, this feature is easy to apply.
